=== alanbraz/complete-json-schema-validator/schemas/model.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "model.schema.json",
  "id": "model.schema.json",
  "title": "Model",
  "description": "Declarative model metadata. Top-level object that contains discovery properties and any combination of the model subobjects. Each model subobject (definition, training, deployment, provenance) corresponds to a stage in the model lifecycle. However, it is possible to be missing information about a model from earlier phases. For example, a trained model binary from a model zoo without code or training information. Model metadata is declarative: it does not include source code, learned weights or parameters, etc. Instead, such artifacts are stored outside of the model metadata, for instance, in git, Jupyter, or cloud object storage, and the model metadata contains pointers to them. ",
  "version": 0.4,
  "type": "object",
  "required": ["name"],
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of model.",
      "example": "examples/simple_example.json#/name"
    },
    "version": {
      "type": "string",
      "description": "Version label for model object.",
      "example": "examples/simple_example.json#/version"
    },
    "description": {
      "type": "string",
      "description": "Long-form description of model.",
      "example": "examples/simple_example.json#/description"
    },
    "authors": {
      "type": "array",
      "description": "Original Authors of the model.",
      "items": {
        "$ref": "model.schema.json#/definitions/authorObject"
      },
      "example": "examples/wml_create_model_example.json#/authors"
    },
    "tags": {
      "type": "array",
      "description": "Assignable tags for model. Contains a user-assignable value. Referenced from WKC.",
      "items": {
        "type": "string"
      },
      "example": "examples/simple_example.json#/tags"
    },
    "domain": {
      "$ref": "model.schema.json#/definitions/domainObject",
      "description": "General domain or field for model.",
      "example": "examples/simple_example.json#/domain"
    },
    "extraction": {
      "type": "array",
      "items": {
        "$ref": "model.schema.json#/definitions/extractObject"
      },
      "description": "Details of automated extractors that this model is based from.",
      "example": "examples/tensorflow_zoo_example.json#/extraction"
    },
    "references": {
       "type": "array",
       "items": {
         "$ref": "model.schema.json#/definitions/refObject"
       },
       "description": "References such as academic papers that this model is based from."
     },
     "visibility": {
       "$ref": "model.schema.json#/definitions/visibilityObject",
       "description": "Visibility of the model, public or private. Also contains information about the license or owner.",
       "example": "examples/simple_example.json#/visibility"
     },
    "definition": {
      "$ref": "model.definition.schema.json",
      "example": "examples/tensorflow_zoo_example.json#/definition"
    },
    "training": {
      "$ref": "model.training.schema.json",
      "example": "examples/wml_create_model_example.json#/training"
    },
    "trained_model": {
      "$ref": "model.trained_model.schema.json",
      "example": "examples/caffe2_zoo_example.json#/trained_model"
    },
    "evaluations": {
      "$ref": "model.evaluations.schema.json",
      "example": "examples/evaluation_example.json#/evaluations"
    },
    "provenance": {
      "$ref": "model.provenance.schema.json",
      "example": "examples/bias_example.json#/provenance"
    },
    "pipeline": {
      "type": "object"
    },
    "id": {
      "type": "string"
    },
    "catalog_metadata": {
      "type": "object"
    },
    "_id": {
      "type": "string"
    },
    "_rev": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "domainObject": {
      "type": "object",
      "required": [
        "domain_type"
      ],
      "properties": {
        "tasks": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The tasks or application problems the model addresses"
        },
        "industries": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The industries which get influenced using the model"
        },
        "domain_type": {
          "type": "string",
          "description": "The type of the domain area that is being addressed by the model"
        }
      }
    },
    "refObject": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "title": {
          "type": "string"
        },
        "authors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "extractObject": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "confidence": {
          "type": "number"
        },
        "completeness": {
          "type": "number"
        }
      }
    },
    "visibilityObject": {
      "type": "object",
      "required": [
        "visibility"
      ],
      "properties": {
        "visibility": {
          "enum": ["public", "private"]
        },
        "license": {
          "type": "string",
          "description": "Type of license model code is released under."
        },
        "owner": {
          "$ref": "model.schema.json#/definitions/authorObject"
        },
        "business_unit": {
          "type": "string"
        },
        "department": {
          "type": "string"
        },
        "organization": {
          "type": "string"
        },
        "division": {
          "type": "string"
        }
      }
    },
    "authorObject": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "github_id": {
          "type": "string"
        },
        "business_unit": {
          "type": "string"
        },
        "department": {
          "type": "string"
        },
        "organization": {
          "type": "string"
        },
        "division": {
          "type": "string"
        }
      }
    }
  }
}

=== alanbraz/complete-json-schema-validator/examples/wml_create_model_example.json
{
  "name": "myModel",
  "description": "This is my model",
  "authors": [
    {"name": "John Smith"}
  ],
  "tags": [ "wml example" ],
  "training": {
    "datasets": [
      {
        "name": "my_name",
        "type": "training",
        "connection": {
          "name": "object_storage",
          "connection": {
            "auth_url": "https://identity.open.softlayer.com",
            "projectId": "f771e5d082e24857adb7554d15fc357c",
            "region": "dallas",
            "userId": "user_name",
            "password": "password"
          },
          "source": {
            "container": "batchjob",
            "filename": "inputData.csv",
            "fileformat": "csv",
            "inferschema": 1,
            "firstlineheader": true,
            "type": "bluemixobjectstorage"
          }
        }
      }
    ],
    "training_output": {
      "name": "object_storage",
      "connection": {
        "access_key_id": "aabbbccMhAI8BGNxuknp",
        "secret_access_key": "bbbcccMhAI8BGNxuknp",
        "endpoint_url": "https://s3-api.dal-us-geo.objectstorage.softlayer.net"
      },
      "source": {
        "bucket": "my-models",
        "key": "my-model",
        "type": "s3"
      }
    }
  },
  "evaluations": [{
    "evaluation_type": "training_evaluation",
    "method": "binary",
    "metrics": [
      {
        "name": "areaUnderROC",
        "threshold": 0.9,
        "value": 0.94
      }
    ]
  }]
}

=== alanbraz/complete-json-schema-validator/examples/text_matching_example.json
{
  "name": "Bilateral Multi-Perspective Matching for Natural Language Sentences",
  "authors": [
    {"name": "ZhiguoWang"},
    {"name": "Wael Hamza"},
    {"name": "Radu Florian"}
  ],
  "domain": {
    "domain_type": "NLP",
    "tasks": ["paraphrase identification", "natural language inference", "answer sentence selection"]
  },
  "references": [
    {
      "title": "Bilateral Multi-Perspective Matching for Natural Language Sentences",
      "authors": ["ZhiguoWang", "Wael Hamza", "Radu Florian"],
      "url": "https: //arxiv.org/abs/1702.03814"
    }
  ],
  "extraction": [{
    "type": "arxiv",
    "confidence": 0.6,
    "completeness": 0.5,
    "url": "https: //arxiv.org/abs/1702.03814"
  }],
  "definition": {
    "code": [{
      "type": "repo",
      "repo_type": "github",
      "url": "https://zhiguowang.github.io/"
    }]
  },
  "training": {
    "datasets": [{
        "Type": "Text",
        "Format": "gzip",
        "Tasks": "Classification",
        "Sub-Tasks": "",
        "Source": "https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs",
        "Name": "Quora Question Pairs",
        "Info": "",
        "Split": "380000,1000,1000",
        "Metrics": "Accuracy",
        "data_preprocessing": {
          "normalization": "mean variance normalization"
        }
      },
      {
        "Type": "Text",
        "Format": "gzip",
        "Tasks": "Classification",
        "Sub-Tasks": "",
        "Source": "https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs",
        "Name": "SNLI",
        "Info": "",
        "Split": "",
        "Metrics": "Accuracy"
      },
      {
        "Type": "Text",
        "Format": "gzip",
        "Tasks": "Classification",
        "Sub-Tasks": "",
        "Source": "https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs",
        "Name": "TREC-QA",
        "Info": "",
        "Split": "",
        "Metrics": "Accuracy"
      },
      {
        "Type": "Text",
        "Format": "gzip",
        "Tasks": "Classification",
        "Sub-Tasks": "",
        "Source": "https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs",
        "Name": "WikiQA",
        "Info": "",
        "Split": "",
        "Metrics": "Accuracy"
      }
    ]
  }
}

=== alanbraz/complete-json-schema-validator/test/examples/hyperparameter_example.json
{
  "name": "MNIST in Tensorflow with hyperparameters",
  "description": "Usage of hyperparameter schema example",
  "extraction": [{
    "type": "github",
    "url": "https://github.com/tensorflow/models/tree/master/official/mnist"
  }],
  "definition": {
    "code": [
      {
        "type": "code",
        "name": "mnist.py",
        "framework": {
          "name": "tensorflow",
          "version": "r1.8"
        },
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py"
          }
        }
      }
    ],
    "hyperparameter_schema": {
      "type": "object",
      "required": ["learning_rate", "num_gpus", "batch_size", "train_epochs"],
      "properties": {
        "learning_rate": {
          "type": "number"
        },
        "num_gpus": {
          "type": "number"
        },
        "batch_size": {
          "type": "number"
        },
        "train_epochs": {
          "type": "number"
        }
      }
    }
  },
  "training": {
    "hyperparameters": {
      "learning_rate": 0.001,
      "num_gpus": 1,
      "batch_size": 100,
      "train_epochs": 40
    }
  }
}

=== alanbraz/complete-json-schema-validator/examples/tensorflow_wml_example.json
{
  "name": "MNIST in Tensorflow, trained in WML",
  "description": "Example from https://github.com/tensorflow/models/tree/master/official/mnist",
  "definition": {
    "code": [
      {
        "type": "code",
        "name": "mnist.py",
        "framework": {
          "name": "tensorflow",
          "version": "r1.8"
        },
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py"
          }
        }
      }
    ]
  },
  "training": {
    "datasets": [
      {
        "name": "mnist",
        "type": "training",
        "connection": {
          "name": "object_storage",
          "connection": {
            "auth_url": "https://identity.open.softlayer.com",
            "projectId": "f771e5d082e24857adb7554d15fc357c",
            "region": "dallas",
            "userId": "user_name",
            "password": "password"
          },
          "source": {
            "container": "batchjob",
            "filename": "train-images-idx3-ubyte.gz",
            "fileformat": "gz",
            "inferschema": 1,
            "firstlineheader": true,
            "type": "bluemixobjectstorage"
          }
        }
      }
    ],
    "training_output": {
      "name": "object_storage",
      "connection": {
        "access_key_id": "aabbbccMhAI8BGNxuknp",
        "secret_access_key": "bbbcccMhAI8BGNxuknp",
        "endpoint_url": "https://s3-api.dal-us-geo.objectstorage.softlayer.net"
      },
      "source": {
        "bucket": "my-models",
        "key": "my-model",
        "type": "s3"
      }
    }
  }
}
