=== alanbraz/complete-json-schema-validator/schemas/model.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "model.schema.json",
  "id": "model.schema.json",
  "title": "Model",
  "description": "Declarative model metadata. Top-level object that contains discovery properties and any combination of the model subobjects. Each model subobject (definition, training, deployment, provenance) corresponds to a stage in the model lifecycle. However, it is possible to be missing information about a model from earlier phases. For example, a trained model binary from a model zoo without code or training information. Model metadata is declarative: it does not include source code, learned weights or parameters, etc. Instead, such artifacts are stored outside of the model metadata, for instance, in git, Jupyter, or cloud object storage, and the model metadata contains pointers to them. ",
  "version": 0.4,
  "type": "object",
  "required": ["name"],
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of model.",
      "example": "examples/simple_example.json#/name"
    },
    "version": {
      "type": "string",
      "description": "Version label for model object.",
      "example": "examples/simple_example.json#/version"
    },
    "description": {
      "type": "string",
      "description": "Long-form description of model.",
      "example": "examples/simple_example.json#/description"
    },
    "authors": {
      "type": "array",
      "description": "Original Authors of the model.",
      "items": {
        "$ref": "model.schema.json#/definitions/authorObject"
      },
      "example": "examples/wml_create_model_example.json#/authors"
    },
    "tags": {
      "type": "array",
      "description": "Assignable tags for model. Contains a user-assignable value. Referenced from WKC.",
      "items": {
        "type": "string"
      },
      "example": "examples/simple_example.json#/tags"
    },
    "domain": {
      "$ref": "model.schema.json#/definitions/domainObject",
      "description": "General domain or field for model.",
      "example": "examples/simple_example.json#/domain"
    },
    "extraction": {
      "type": "array",
      "items": {
        "$ref": "model.schema.json#/definitions/extractObject"
      },
      "description": "Details of automated extractors that this model is based from.",
      "example": "examples/tensorflow_zoo_example.json#/extraction"
    },
    "references": {
       "type": "array",
       "items": {
         "$ref": "model.schema.json#/definitions/refObject"
       },
       "description": "References such as academic papers that this model is based from."
     },
     "visibility": {
       "$ref": "model.schema.json#/definitions/visibilityObject",
       "description": "Visibility of the model, public or private. Also contains information about the license or owner.",
       "example": "examples/simple_example.json#/visibility"
     },
    "definition": {
      "$ref": "model.definition.schema.json",
      "example": "examples/tensorflow_zoo_example.json#/definition"
    },
    "training": {
      "$ref": "model.training.schema.json",
      "example": "examples/wml_create_model_example.json#/training"
    },
    "trained_model": {
      "$ref": "model.trained_model.schema.json",
      "example": "examples/caffe2_zoo_example.json#/trained_model"
    },
    "evaluations": {
      "$ref": "model.evaluations.schema.json",
      "example": "examples/evaluation_example.json#/evaluations"
    },
    "provenance": {
      "$ref": "model.provenance.schema.json",
      "example": "examples/bias_example.json#/provenance"
    },
    "pipeline": {
      "type": "object"
    },
    "id": {
      "type": "string"
    },
    "catalog_metadata": {
      "type": "object"
    },
    "_id": {
      "type": "string"
    },
    "_rev": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "domainObject": {
      "type": "object",
      "required": [
        "domain_type"
      ],
      "properties": {
        "tasks": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The tasks or application problems the model addresses"
        },
        "industries": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The industries which get influenced using the model"
        },
        "domain_type": {
          "type": "string",
          "description": "The type of the domain area that is being addressed by the model"
        }
      }
    },
    "refObject": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "title": {
          "type": "string"
        },
        "authors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "extractObject": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "confidence": {
          "type": "number"
        },
        "completeness": {
          "type": "number"
        }
      }
    },
    "visibilityObject": {
      "type": "object",
      "required": [
        "visibility"
      ],
      "properties": {
        "visibility": {
          "enum": ["public", "private"]
        },
        "license": {
          "type": "string",
          "description": "Type of license model code is released under."
        },
        "owner": {
          "$ref": "model.schema.json#/definitions/authorObject"
        },
        "business_unit": {
          "type": "string"
        },
        "department": {
          "type": "string"
        },
        "organization": {
          "type": "string"
        },
        "division": {
          "type": "string"
        }
      }
    },
    "authorObject": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "github_id": {
          "type": "string"
        },
        "business_unit": {
          "type": "string"
        },
        "department": {
          "type": "string"
        },
        "organization": {
          "type": "string"
        },
        "division": {
          "type": "string"
        }
      }
    }
  }
}

=== alanbraz/complete-json-schema-validator/examples/ibm_internal_example.json
{
  "name": "WatsonNET",
  "version": "v0.3",
  "description": "Implementation of WatsonNET",
  "domain": {
    "domain_type": "Vision",
    "tasks": ["Image Classification"]
  },
  "tags": [ "watsonnet", "ibm internal example" ],
  "visibility": {
    "visibility": "private",
    "business_unit": "IBM Research",
    "division": "Research AI",
    "organziation": "Watson Research Lab"
  }
}

=== alanbraz/complete-json-schema-validator/examples/tensorflow_wml_full_example.json
{
  "name": "MNIST in Tensorflow, trained in WML",
  "description": "Example from https://github.com/tensorflow/models/tree/master/official/mnist",
  "definition": {
    "code": [
      {
        "type": "code",
        "name": "mnist.py",
        "framework": {
          "name": "tensorflow",
          "version": "r1.8"
        },
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py"
          }
        }
      },
      {
        "type": "code",
        "name": "dataset.py",
        "framework": {
          "name": "tensorflow",
          "version": "r1.8"
        },
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/tensorflow/models/blob/master/official/mnist/dataset.py"
          }
        }
      }
    ],
    "topology": {
      "type": "cnn",
      "layers": [
        {
          "type": "reshape",
          "target_shape": [1, 28, 28]
        },
        {
          "type": "conv2d",
          "activation": "relu"
        },
        {
          "type": "max_pool"
        },
        {
          "type": "conv2d",
          "activation": "relu"
        },
        {
          "type": "max_pool"
        },
        {
          "type": "flatten"
        },
        {
          "type": "dense",
          "units": 1024,
          "activation": "relu"
        },
        {
          "type": "dropout",
          "keep_prob": 0.4
        },
        {
          "type": "dense",
          "units": 10
        }
      ]
    }
  },
  "training": {
    "datasets": [
      {
        "name": "mnist",
        "type": "training",
        "connection": {
          "name": "object_storage",
          "connection": {
            "auth_url": "https://identity.open.softlayer.com",
            "projectId": "f771e5d082e24857adb7554d15fc357c",
            "region": "dallas",
            "userId": "user_name",
            "password": "password"
          },
          "source": {
            "container": "batchjob",
            "filename": "train-images-idx3-ubyte.gz",
            "fileformat": "gz",
            "inferschema": 1,
            "firstlineheader": true,
            "type": "bluemixobjectstorage"
          }
        },
        "data_preprocessing": {
          "operators": ["normalization", "scaling"],
          "noise_removers": ["filtering"]
        }
      }
    ],
    "hyperparameters": {
      "learning_rate": 0.001,
      "batch_size": 100,
      "train_epochs": 40
    },
    "training_output": {
      "name": "object_storage",
      "connection": {
        "access_key_id": "aabbbccMhAI8BGNxuknp",
        "secret_access_key": "bbbcccMhAI8BGNxuknp",
        "endpoint_url": "https://s3-api.dal-us-geo.objectstorage.softlayer.net"
      },
      "source": {
        "bucket": "my-models",
        "key": "my-model",
        "type": "s3"
      }
    }
  }
}

=== alanbraz/complete-json-schema-validator/test/examples/tensorflow_zoo_example.json
{
  "name": "MNIST in Tensorflow",
  "description": "Example from https://github.com/tensorflow/models/tree/master/official/mnist",
  "extraction": [{
    "type": "github",
    "url": "https://github.com/tensorflow/models/tree/master/official/mnist"
  }],
  "definition": {
    "code": [
      {
        "type": "code",
        "name": "mnist.py",
        "framework": {
          "name": "tensorflow",
          "version": "r1.8"
        },
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py"
          }
        }
      }
    ]
  }
}

=== alanbraz/complete-json-schema-validator/test/examples/bias_example.json
{
  "name": "bias checker output",
  "description": "Resulting model from running de-biasing, based on #38",
  "provenance": {
    "previous_model_id": "1",
    "modifications": [
      {
        "type": "bias",
        "modification_date": "2018-05-07T18:25:43.511Z",
        "details": {
          "checker": {
            "description": "bias checker",
            "version": "v1"
          },
          "de_biaser_parameters": [0, 1, 2],
          "confidence": 0.90
        }
      }
    ]
  },
  "evaluations": [
    {
      "evaluation_type": "bias",
      "biasValue": 0,
      "class": "",
      "description": "",
      "type": "data_bias"
    }
  ]
}

=== alanbraz/complete-json-schema-validator/examples/max_inception_example.json
{
  "name": "IBM Code Model Asset Exchange: Inception-ResNet-v2 on ImageNet",
  "description": "Keras offers many imagenet models, this one has the highest accuracy. From https://github.com/IBM/MAX-Inception-ResNet-v2",
  "domain": {
    "domain_type": "Vision",
    "tasks": ["Image Classification"],
    "industries": ["General"]
  },
  "references": [{
    "title": "Inception-v4, Inception-ResNet and the Impact of Residual Connections on Learning",
    "authors": ["C. Szegedy", "S. Ioffe", "V. Vanhoucke", "A. Alemi"],
    "url": "https://arxiv.org/abs/1602.07261",
    "arxiv": "1602.07261"
  }],
  "trained_model": {
    "binaries": [
      {
        "name": "Dockerfile",
        "type": "Dockerfile",
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/IBM/MAX-Inception-ResNet-v2/blob/master/Dockerfile"
          }
        },
        "framework": {
          "name": "Keras",
          "license": "MIT"
        },
        "license": "Apache 2.0"
      },
      {
        "name": "app.py",
        "type": "Python",
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/IBM/MAX-Inception-ResNet-v2/blob/master/app.py"
          }
        },
        "framework": {
          "name": "Keras",
          "license": "MIT"
        },
        "license": "Apache 2.0"
      },
      {
        "name": "config.py",
        "type": "Python",
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/IBM/MAX-Inception-ResNet-v2/blob/master/config.py"
          }
        },
        "framework": {
          "name": "Keras",
          "license": "MIT"
        },
        "license": "Apache 2.0"
      },
      {
        "name": "api/model.py",
        "type": "Python",
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/IBM/MAX-Inception-ResNet-v2/blob/master/api/model.py"
          }
        },
        "framework": {
          "name": "Keras",
          "license": "MIT"
        },
        "license": "Apache 2.0"
      },
      {
        "name": "api/__init__.py",
        "type": "Python",
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/IBM/MAX-Inception-ResNet-v2/blob/master/api/__init__.py"
          }
        },
        "framework": {
          "name": "Keras",
          "license": "MIT"
        },
        "license": "Apache 2.0"
      }
    ],
    "input_data_def": {
      "type": "image",
      "color": "rgb/hwc",
      "width": 299,
      "height": 299
    }
  }
}

=== alanbraz/complete-json-schema-validator/test/examples/max_adversarialcrypto_example.json
{
  "name": "IBM Code Model Asset Exchange: Adversarial Cryptography Experiment",
  "references": [{
    "title": "Learning to Protect Communications with Adversarial Neural Cryptograph",
    "authors": ["M. Abadi", "D. Andersen"],
    "url": "https://arxiv.org/abs/1610.06918",
    "arxiv": "1610.06918"
  }],
  "extraction": [
    {
      "type": "github",
      "url": "https://github.com/IBM/MAX-Adversarial-Cryptography"
    }
  ],
  "definition": {
    "code": [
      {
        "type": "code",
        "name": "adverserial_crypto.zip",
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/IBM/MAX-Adversarial-Cryptography/blob/master/adverserial_crypto.zip"
          }
        },
        "license": "Apache 2.0",
        "framework": {
          "name": "tensorflow",
          "version": "1.5"
        }
      },
      {
        "type": "code",
        "name": "run.sh",
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/IBM/MAX-Adversarial-Cryptography/blob/master/run.sh"
          }
        },
        "license": "Apache 2.0"
      }
    ]
  },
  "training": {
    "training_job": {
      "type": "wml"
    },
    "datasets": [
        {
            "name": "training reference",
            "type": "training",
            "connection": {
              "name": "(training-data-reference_name)",
              "type": "training",
              "connection": {
                "type": "s3",
                "endpoint_url": "https://s3-api.us-geo.objectstorage.service.networklayer.com",
                "access_key_id": "(FILL IN)",
                "secret_access_key": "(FILL IN)"
              },
              "source": {
                "bucket": "adversarial-crypto-training"
              }
            }
        }
    ],
    "training_output": {
      "name": "(training-results-reference_name)",
      "connection": {
        "type": "s3",
        "endpoint_url": "https://s3-api.us-geo.objectstorage.service.networklayer.com",
        "access_key_id": "(FILL IN)",
        "secret_access_key": "(FILL IN)"
      },
      "source": {
        "bucket": "adversarial-crypto-training-results"
      }
    }
  }
}

=== alanbraz/complete-json-schema-validator/test/examples/simple_example.json
{
  "name": "AlexNET",
  "version": "v0.3",
  "description": "Implementation of AlexNET",
  "domain": {
    "domain_type": "Vision",
    "tasks": ["Image Classification"]
  },
  "tags": [ "alexnet", "canonical example" ],
  "references": [{
    "title": "ImageNet Classification with Deep Convolutional Neural Networks",
    "authors": [
      "Alex Krizhevsky", "Ilya Sutskever", "Geoffrey E. Hinton"
    ],
    "url": "http://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks"
  }],
  "visibility": {
    "visibility": "public",
    "license": "MIT License"
  }
}

=== alanbraz/complete-json-schema-validator/test/examples/tensorflow_regression_full_example.json
{
  "name": "Linear regression in Tensorflow, trained in WML",
  "description": "Example from https://github.com/tensorflow/models/tree/master/samples/cookbook/regression",
  "definition": {
    "code": [
      {
        "type": "code",
        "name": "linear_regression.py",
        "framework": {
          "name": "tensorflow",
          "version": "r1.8"
        },
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/tensorflow/models/blob/master/samples/cookbook/regression/linear_regression.py"
          }
        }
      },
      {
        "type": "code",
        "name": "automobile_data.py",
        "framework": {
          "name": "tensorflow",
          "version": "r1.8"
        },
        "connection": {
          "name": "github_url",
          "connection": { },
          "source": {
            "url": "https://github.com/tensorflow/models/blob/master/samples/cookbook/regression/automobile_data.py"
          }
        }
      }
    ],
    "topology": {
      "type": "linear regression"
    }
  },
  "training": {
    "datasets": [
      {
        "name": "auotmobile_data",
        "type": "training",
        "connection": {
          "name": "object_storage",
          "connection": {
            "auth_url": "https://identity.open.softlayer.com",
            "projectId": "f771e5d082e24857adb7554d15fc357c",
            "region": "dallas",
            "userId": "user_name",
            "password": "password"
          },
          "source": {
            "container": "batchjob",
            "filename": "imports-85.data",
            "fileformat": "gz",
            "inferschema": 1,
            "firstlineheader": true,
            "type": "bluemixobjectstorage"
          }
        },
        "data_preprocessing": {
          "operators": ["normalization", "scaling"],
          "noise_removers": ["filtering"]
        }
      }
    ],
    "hyperparameters": {
      "batch_size": 100,
      "train_steps": 1000,
      "price_norm_factor": 1000
    },
    "features": {
      "columns": ["curb-weight", "highway-mpg"]
    },
    "training_output": {
      "name": "object_storage",
      "connection": {
        "access_key_id": "aabbbccMhAI8BGNxuknp",
        "secret_access_key": "bbbcccMhAI8BGNxuknp",
        "endpoint_url": "https://s3-api.dal-us-geo.objectstorage.softlayer.net"
      },
      "source": {
        "bucket": "my-models",
        "key": "my-model",
        "type": "s3"
      }
    }
  }
}
